version: 2.1

jobs:
  build:
    docker:
      - image: ruby:3.2

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install

      - run:
          name: Run tests
          command: echo "Les tests sont en cours d'écriture"
